# Generated by Django 4.2.1 on 2023-05-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryName', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
    ]
