# Generated by Django 4.2.1 on 2023-05-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0002_report_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularUser',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
