# Generated by Django 4.2.1 on 2023-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0003_regularuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
