# Generated by Django 4.2.1 on 2023-05-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0006_comment_usertype_report_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='originalPoster',
            field=models.CharField(max_length=150),
        ),
    ]
