# Generated by Django 4.2.1 on 2023-05-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0007_alter_comment_originalposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parentID',
            field=models.CharField(max_length=256),
        ),
    ]
