# Generated by Django 4.2.1 on 2023-05-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0009_alter_comment_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parentID',
            field=models.CharField(max_length=256),
        ),
    ]
