# Generated by Django 4.2.1 on 2023-05-28 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskapp', '0010_alter_comment_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdeskapp.report'),
        ),
    ]
